# Generated by Django 5.0.6 on 2025-03-29 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_file', models.FileField(help_text='Upload an MP4 video file', upload_to='videos/tutorials/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_tutorials', to='app.instrument')),
            ],
        ),
        migrations.DeleteModel(
            name='AdminLog',
        ),
    ]
