# Generated by Django 5.1.6 on 2025-04-05 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_videotutorial_delete_adminlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='regions/')),
            ],
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='origin',
        ),
        migrations.AddField(
            model_name='instrument',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments', to='app.region'),
        ),
        migrations.DeleteModel(
            name='Tribe',
        ),
    ]
