# Generated by Django 5.1.6 on 2025-04-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_region_remove_instrument_origin_instrument_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
