# Generated by Django 5.0.6 on 2025-05-01 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MVCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('mission', 'Mission'), ('vision', 'Vision'), ('objective', 'Objective'), ('advocacy', 'Advocacy')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('accent_color', models.CharField(help_text='Hex color code, e.g., #FF6B6B', max_length=7)),
                ('is_list', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MVSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Guiding Principles', max_length=200)),
                ('intro_text', models.TextField()),
                ('image', models.ImageField(help_text='Upload the section image (e.g., phil.png)', upload_to='mv_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='region',
            name='image',
        ),
        migrations.CreateModel(
            name='InstrumentMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instrument')),
                ('materials', models.ManyToManyField(related_name='instruments', to='app.material')),
            ],
        ),
        migrations.CreateModel(
            name='MVCardListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='app.mvcard')),
            ],
        ),
    ]
