# Generated by Django 5.0.6 on 2025-05-01 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_mvcard_mvsection_remove_instrument_materials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidingPrinciples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Guiding Principles', max_length=255)),
                ('description', models.TextField(default='We believe in the transformative power of music education to enrich lives and build communities.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='PrincipleCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('Mission', 'Mission'), ('Vision', 'Vision'), ('Objective', 'Objective'), ('Advocacy', 'Advocacy')], max_length=20)),
                ('icon_svg_path', models.TextField(help_text='Paste the SVG path data here.')),
                ('accent_color', models.CharField(help_text='Enter a hex color code, e.g. #FF6B6B', max_length=7)),
                ('description', models.TextField(blank=True, null=True)),
                ('bullet_points', models.TextField(blank=True, help_text='If card has a list (like Objective), separate items with a new line.', null=True)),
                ('guiding_principles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='app.guidingprinciples')),
            ],
        ),
        migrations.RemoveField(
            model_name='mvcardlistitem',
            name='card',
        ),
        migrations.DeleteModel(
            name='MVSection',
        ),
        migrations.DeleteModel(
            name='MVCard',
        ),
        migrations.DeleteModel(
            name='MVCardListItem',
        ),
    ]
