# Generated by Django 5.0.6 on 2025-05-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_guidingprinciples_principlecard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Discover Traditional Instruments', max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('mastering_title', models.CharField(default='Mastering', max_length=255)),
                ('mastering_paragraph1', models.TextField()),
                ('mastering_paragraph2', models.TextField()),
                ('mastering_button_text', models.CharField(default='Explore Curriculum', max_length=255)),
                ('mastering_button_url', models.URLField(default='#')),
                ('video1', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('video2', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('video_description', models.TextField(default='Listen to the mesmerizing tones of traditional sitar music')),
            ],
        ),
    ]
