# Generated by Django 5.0.6 on 2025-05-04 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_discoversection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discoversection',
            name='mastering_button_text',
        ),
        migrations.RemoveField(
            model_name='discoversection',
            name='mastering_button_url',
        ),
    ]
