# Generated by Django 5.0.6 on 2025-05-11 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_discoversection_mastering_button_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='sound_sample',
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('sound_sample', models.FileField(blank=True, null=True, upload_to='instruments/sounds/')),
                ('Instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instrument')),
            ],
        ),
    ]
