# Generated by Django 5.0.6 on 2025-05-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_instrument_sound_sample_sound'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(default='Contact Philharmonia', help_text='Main title for the contact page header', max_length=200)),
                ('header_description', models.TextField(default='Have questions about Philippine traditional instruments? Want to collaborate or share your knowledge? Reach out to us!', help_text='Subtitle text under the main header title')),
                ('section_title', models.CharField(default='Get In Touch', help_text='Title for the contact information section', max_length=200)),
                ('location_title', models.CharField(default='Our Location', help_text='Title for location information', max_length=200)),
                ('location_address', models.TextField(default='National Music Museum\nManila, Philippines 1000', help_text='Full address with line breaks (use Shift+Enter for new lines)')),
                ('phone_title', models.CharField(default='Phone Numbers', help_text='Title for phone numbers section', max_length=200)),
                ('landline_phone', models.CharField(default='+63 2 8123 4567', help_text='Format: +63 2 8123 4567', max_length=20)),
                ('mobile_phone', models.CharField(default='+63 917 123 4567', help_text='Format: +63 917 123 4567', max_length=20)),
                ('email_title', models.CharField(default='Email Address', help_text='Title for email addresses section', max_length=200)),
                ('primary_email', models.EmailField(default='info@philharmonia.ph', help_text='Primary contact email', max_length=254)),
                ('secondary_email', models.EmailField(default='support@philharmonia.ph', help_text='Secondary contact email', max_length=254)),
                ('hours_title', models.CharField(default='Operating Hours', help_text='Title for operating hours section', max_length=200)),
                ('weekdays_hours', models.CharField(default='Monday to Friday: 9:00 AM - 6:00 PM', help_text='Weekday hours format', max_length=100)),
                ('saturday_hours', models.CharField(default='Saturday: 10:00 AM - 4:00 PM', help_text='Saturday hours format', max_length=100)),
                ('sunday_hours', models.CharField(default='Sunday: Closed', help_text='Sunday hours format', max_length=100)),
                ('form_title', models.CharField(default='Send Us a Message', help_text='Title for the contact form section', max_length=200)),
            ],
            options={
                'verbose_name': 'Contact Page Content',
                'verbose_name_plural': 'Contact Page Content',
            },
        ),
        migrations.RenameField(
            model_name='sound',
            old_name='Instrument',
            new_name='instrument',
        ),
        migrations.AddField(
            model_name='instrumentcategory',
            name='icon',
            field=models.CharField(default='fa-music', max_length=50),
        ),
        migrations.AddField(
            model_name='videotutorial',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
