# Generated by Django 5.0.6 on 2025-05-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(choices=[('General Inquiry', 'General Inquiry'), ('Instrument Information', 'Instrument Information'), ('Workshop Registration', 'Workshop Registration'), ('Collaboration', 'Collaboration'), ('Feedback/Suggestions', 'Feedback/Suggestions')], max_length=50),
        ),
    ]
