# Generated by Django 5.0.6 on 2025-05-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_contactmessage_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='principlecard',
            name='icon_svg_path',
        ),
        migrations.AddField(
            model_name='principlecard',
            name='icon',
            field=models.CharField(default='fa-music', max_length=50),
        ),
    ]
