# Generated by Django 5.0.6 on 2025-05-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_principlecard_icon_svg_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='email_title',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='form_title',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='hours_title',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='location_title',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='phone_title',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='section_title',
        ),
    ]
