# Generated by Django 5.0.6 on 2025-05-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_culturalimportance_targetaudience_teammember_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='front_description',
        ),
    ]
