# Generated by Django 5.1.6 on 2025-05-28 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_teammember_front_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_type', models.CharField(choices=[('front', 'Front View'), ('side', 'Side View'), ('detail', 'Detail View')], default='other', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='instruments/detailed/images/')),
                ('caption', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.instrument')),
            ],
            options={
                'verbose_name_plural': 'Instrument Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
