# Generated by Django 5.1.6 on 2025-05-28 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_instrumentimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechniqueStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('video_tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technique_steps', to='app.videotutorial')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tooltip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('definition', models.TextField()),
                ('technique_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tooltips', to='app.techniquestep')),
            ],
        ),
    ]
