# Generated by Django 5.1.6 on 2025-05-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_techniquestep_tooltip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tooltip',
        ),
    ]
