# Generated by Django 5.1.6 on 2025-05-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_constructionstep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='is_front',
        ),
    ]
