# Generated by Django 5.1.6 on 2025-06-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_sociallink_is_front'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offering',
            options={'verbose_name': 'Offering', 'verbose_name_plural': 'Offerings'},
        ),
        migrations.RemoveField(
            model_name='offering',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='offering',
            name='order',
        ),
        migrations.AlterField(
            model_name='techniquestep',
            name='step_number',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='constructionstep',
            unique_together={('instrument', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='techniquestep',
            unique_together={('video_tutorial', 'step_number')},
        ),
    ]
