# Generated by Django 5.1.6 on 2025-06-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_offering_options_remove_offering_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniquestep',
            name='step_number',
            field=models.PositiveIntegerField(),
        ),
    ]
