# Generated by Django 5.1.6 on 2025-06-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_techniquestep_step_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offering',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Offering', 'verbose_name_plural': 'Offerings'},
        ),
        migrations.AlterUniqueTogether(
            name='constructionstep',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='offering',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offering',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='techniquestep',
            name='step_number',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
