# Generated by Django 5.1.6 on 2025-06-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_offering_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offering',
            options={'verbose_name': 'Offering', 'verbose_name_plural': 'Offerings'},
        ),
        migrations.RemoveField(
            model_name='offering',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='offering',
            name='order',
        ),
        migrations.AlterUniqueTogether(
            name='constructionstep',
            unique_together={('instrument', 'order')},
        ),
    ]
