# Generated by Django 5.1.6 on 2025-06-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_offering_options_remove_offering_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='culturalimportance',
            options={'verbose_name': 'Cultural Importance Item', 'verbose_name_plural': 'Cultural Importance Items'},
        ),
        migrations.AlterModelOptions(
            name='targetaudience',
            options={'verbose_name': 'Target Audience', 'verbose_name_plural': 'Target Audiences'},
        ),
        migrations.RemoveField(
            model_name='culturalimportance',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='culturalimportance',
            name='order',
        ),
        migrations.RemoveField(
            model_name='targetaudience',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='targetaudience',
            name='order',
        ),
    ]
