# Generated by Django 5.1.6 on 2025-06-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_culturalimportance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='order',
        ),
    ]
