# Generated by Django 5.1.6 on 2025-06-01 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_teammember_options_remove_teammember_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentimage',
            options={'verbose_name_plural': 'Instrument Images'},
        ),
        migrations.RemoveField(
            model_name='instrumentimage',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='instrumentimage',
            name='order',
        ),
    ]
