# Generated by Django 5.0.6 on 2025-06-02 16:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_instrumentimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalSignificance',
            fields=[
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cultural_significance', serialize=False, to='app.instrument')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Cultural Significance',
                'verbose_name_plural': 'Cultural Significance Records',
            },
        ),
    ]
