# Generated by Django 5.0.6 on 2025-06-02 16:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_culturalsignificance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funfact',
            fields=[
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fun_fact', serialize=False, to='app.instrument')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Fun Fact',
                'verbose_name_plural': 'Fun Facts',
            },
        ),
    ]
