# Generated by Django 5.0.6 on 2025-06-02 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_funfact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funfact',
            name='instrument',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='funfact', serialize=False, to='app.instrument'),
        ),
    ]
