# Generated by Django 5.0.6 on 2025-06-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_funfact_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='province',
            field=models.CharField(blank=True, choices=[('Abra', 'Abra'), ('Agusan del Norte', 'Agusan del Norte'), ('Agusan del Sur', 'Agusan del Sur'), ('Aklan', 'Aklan'), ('Albay', 'Albay'), ('Antique', 'Antique'), ('Apayao', 'Apayao'), ('Aurora', 'Aurora'), ('Basilan', 'Basilan'), ('Bataan', 'Bataan'), ('Batanes', 'Batanes'), ('Batangas', 'Batangas'), ('Biliran', 'Biliran'), ('Benguet', 'Benguet'), ('Bohol', 'Bohol'), ('Bukidnon', 'Bukidnon'), ('Bulacan', 'Bulacan'), ('Cagayan', 'Cagayan'), ('Camarines Norte', 'Camarines Norte'), ('Camarines Sur', 'Camarines Sur'), ('Camiguin', 'Camiguin'), ('Capiz', 'Capiz'), ('Catanduanes', 'Catanduanes'), ('Cavite', 'Cavite'), ('Cebu', 'Cebu'), ('Compostela Valley', 'Compostela Valley'), ('Cotabato', 'Cotabato'), ('Davao de Oro', 'Davao de Oro'), ('Davao del Norte', 'Davao del Norte'), ('Davao del Sur', 'Davao del Sur'), ('Davao Occidental', 'Davao Occidental'), ('Davao Oriental', 'Davao Oriental'), ('Dinagat Islands', 'Dinagat Islands'), ('Eastern Samar', 'Eastern Samar'), ('Guimaras', 'Guimaras'), ('Ifugao', 'Ifugao'), ('Ilocos Norte', 'Ilocos Norte'), ('Ilocos Sur', 'Ilocos Sur'), ('Iloilo', 'Iloilo'), ('Isabela', 'Isabela'), ('Kalinga', 'Kalinga'), ('La Union', 'La Union'), ('Laguna', 'Laguna'), ('Lanao del Norte', 'Lanao del Norte'), ('Lanao del Sur', 'Lanao del Sur'), ('Leyte', 'Leyte'), ('Maguindanao', 'Maguindanao'), ('Marinduque', 'Marinduque'), ('Masbate', 'Masbate'), ('Misamis Occidental', 'Misamis Occidental'), ('Misamis Oriental', 'Misamis Oriental'), ('Mountain Province', 'Mountain Province'), ('Negros Occidental', 'Negros Occidental'), ('Negros Oriental', 'Negros Oriental'), ('Northern Samar', 'Northern Samar'), ('Nueva Ecija', 'Nueva Ecija'), ('Nueva Vizcaya', 'Nueva Vizcaya'), ('Occidental Mindoro', 'Occidental Mindoro'), ('Oriental Mindoro', 'Oriental Mindoro'), ('Palawan', 'Palawan'), ('Pampanga', 'Pampanga'), ('Pangasinan', 'Pangasinan'), ('Quezon', 'Quezon'), ('Quirino', 'Quirino'), ('Rizal', 'Rizal'), ('Romblon', 'Romblon'), ('Samar', 'Samar'), ('Sarangani', 'Sarangani'), ('Siquijor', 'Siquijor'), ('Sorsogon', 'Sorsogon'), ('South Cotabato', 'South Cotabato'), ('Southern Leyte', 'Southern Leyte'), ('Sultan Kudarat', 'Sultan Kudarat'), ('Sulu', 'Sulu'), ('Surigao del Norte', 'Surigao del Norte'), ('Surigao del Sur', 'Surigao del Sur'), ('Tarlac', 'Tarlac'), ('Tawi-Tawi', 'Tawi-Tawi'), ('Zambales', 'Zambales'), ('Zamboanga del Norte', 'Zamboanga del Norte'), ('Zamboanga del Sur', 'Zamboanga del Sur'), ('Zamboanga Sibugay', 'Zamboanga Sibugay')], max_length=50, null=True),
        ),
    ]
