# Generated by Django 5.1.6 on 2025-06-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_instrument_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('email', 'Email'), ('instagram', 'Instagram'), ('youtube', 'YouTube')], max_length=20),
        ),
    ]
