# Generated by Django 5.1.6 on 2025-06-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_sociallink_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(default='Experience Traditional Filipino Music', max_length=200)),
                ('highlight_word', models.CharField(default='Filipino', max_length=50)),
                ('description', models.TextField(default='Learn about traditional instruments like the Kulintang, Kudyapi, and Gangsa. Explore their unique sounds and the stories behind them. Ready to begin your journey?')),
                ('singleton_instance', models.BooleanField(default=True, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tagline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='🎶', max_length=10)),
                ('title', models.CharField(default='PHILHARMONIA MUSIC', max_length=100)),
            ],
        ),
    ]
