# Generated by Django 5.1.6 on 2025-06-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_homepage_tagline'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_us_title', models.CharField(default='Follow Us', max_length=100, verbose_name='Follow Us Title')),
                ('follow_us_description', models.TextField(default='Stay connected and follow us on our social media platforms', max_length=200, verbose_name='Follow Us Description')),
            ],
            options={
                'verbose_name': 'Footer Settings',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube')], max_length=20, unique=True, verbose_name='Social Media Platform')),
                ('url', models.URLField(help_text='Enter the full URL to your social media profile', verbose_name='Profile URL')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Determines the order in which icons appear (lower numbers first)', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to display this social media link', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
                'ordering': ['display_order', 'platform'],
            },
        ),
        migrations.AlterField(
            model_name='homepage',
            name='description',
            field=models.TextField(default='Explore our web-based platform featuring an interactive map, visual galleries, educational tutorials, and 3D models all dedicated to preserving and promoting traditional Filipino music and heritage.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='highlight_word',
            field=models.CharField(default='Music', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='main_heading',
            field=models.CharField(default='Experience Traditional Filipino', max_length=200),
        ),
    ]
