# Generated by Django 5.1.6 on 2025-06-07 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_footersettings_socialmedialink_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedialink',
            options={'verbose_name': 'Social Media Link', 'verbose_name_plural': 'Social Media Links'},
        ),
        migrations.RemoveField(
            model_name='socialmedialink',
            name='display_order',
        ),
    ]
