# Generated by Django 5.1.6 on 2025-06-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_socialmedialink_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='singleton_instance',
        ),
        migrations.AlterField(
            model_name='tagline',
            name='icon',
            field=models.CharField(default='fa-music', max_length=50),
        ),
    ]
