# Generated by Django 5.1.6 on 2025-06-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_remove_homepage_singleton_instance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagline',
            name='icon',
            field=models.CharField(default='music', max_length=50),
        ),
    ]
