# Generated by Django 5.0.6 on 2025-11-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_lessonappointment_performanceappointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonappointment',
            name='lesson_topic',
        ),
    ]
