# Generated by Django 5.0.6 on 2025-11-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_instrumentforum_instrumentmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='model_3d',
            field=models.FileField(blank=True, help_text='Upload a 3D model file (.glb, .gltf)', null=True, upload_to='instruments/3d_models/'),
        ),
    ]
