# Generated by Django 5.0.6 on 2025-11-14 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_instrument_model_3d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='model_3d',
        ),
        migrations.CreateModel(
            name='Instrument3DModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='Upload a 3D model file (.glb, .gltf)', null=True, upload_to='instruments/3d_models/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='three_d', to='app.instrument')),
            ],
        ),
    ]
