# Generated by Django 5.0.6 on 2025-11-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_remove_instrument_model_3d_instrument3dmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site3DContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Discover Philippine Traditional Instruments', max_length=200)),
                ('hero_description', models.TextField(default='Explore our gallery of authentic Filipino musical heritage with sound samples')),
                ('about_title', models.CharField(default='Preserving Philippine Musical Heritage', max_length=200)),
                ('about_content', models.TextField(default='This project aims to digitally preserve and showcase the rich variety of traditional Philippine musical instruments through images and authentic sound recordings.')),
                ('about_image', models.ImageField(default='site_content/prin.jpg', upload_to='site_content/')),
            ],
            options={
                'verbose_name_plural': 'Site Content',
            },
        ),
    ]
