# Generated by Django 5.0.6 on 2025-11-19 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_site3dcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Link title or description', max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('link_type', models.CharField(choices=[('info', 'Information Source'), ('video', 'Video'), ('audio', 'Audio Sample'), ('image', 'Image Source'), ('research', 'Research Paper'), ('museum', 'Museum Link'), ('other', 'Other')], default='info', max_length=20)),
                ('is_primary_source', models.BooleanField(default=False, help_text='Mark as main information source')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='app.instrument')),
            ],
            options={
                'ordering': ['-is_primary_source', 'link_type', 'title'],
            },
        ),
    ]
