# Generated by Django 5.0.6 on 2025-11-20 05:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_alter_contactmessage_options_contactmessage_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(choices=[('General Inquiry', 'General Inquiry'), ('Instrument Information', 'Instrument Information'), ('Workshop Registration', 'Workshop Registration'), ('Collaboration', 'Collaboration'), ('Feedback/Suggestions', 'Feedback/Suggestions')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
