# Generated by Django 5.0.6 on 2025-11-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_alter_contactmessage_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[('Ilocos Region', 'Ilocos Region (Region I)'), ('Cagayan Valley', 'Cagayan Valley (Region II)'), ('Central Luzon', 'Central Luzon (Region III)'), ('CALABARZON', 'CALABARZON (Region IV-A)'), ('MIMAROPA', 'MIMAROPA (Region IV-B)'), ('Bicol Region', 'Bicol Region (Region V)'), ('Western Visayas', 'Western Visayas (Region VI)'), ('Central Visayas', 'Central Visayas (Region VII)'), ('Eastern Visayas', 'Eastern Visayas (Region VIII)'), ('Zamboanga Peninsula', 'Zamboanga Peninsula (Region IX)'), ('Northern Mindanao', 'Northern Mindanao (Region X)'), ('Davao Region', 'Davao Region (Region XI)'), ('SOCCSKSARGEN', 'SOCCSKSARGEN (Region XII)'), ('Caraga', 'Caraga (Region XIII)'), ('Cordillera Administrative Region', 'Cordillera Administrative Region (CAR)'), ('Bangsamoro', 'Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)')], max_length=100, unique=True),
        ),
    ]
