# Generated by Django 5.0.6 on 2025-12-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_region_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonappointment',
            name='decline_reason',
            field=models.TextField(blank=True, help_text='Reason for declining the appointment', null=True),
        ),
        migrations.AddField(
            model_name='performanceappointment',
            name='decline_reason',
            field=models.TextField(blank=True, help_text='Reason for declining the appointment', null=True),
        ),
        migrations.AlterField(
            model_name='discoversection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/images/'),
        ),
        migrations.AlterField(
            model_name='discoversection',
            name='video1',
            field=models.FileField(blank=True, null=True, upload_to='images/videos/'),
        ),
        migrations.AlterField(
            model_name='discoversection',
            name='video2',
            field=models.FileField(blank=True, null=True, upload_to='images/videos/'),
        ),
        migrations.AlterField(
            model_name='guidingprinciples',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/images/'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/instruments/images/'),
        ),
        migrations.AlterField(
            model_name='instrument3dmodel',
            name='file',
            field=models.FileField(blank=True, help_text='Upload a 3D model file (.glb, .gltf)', null=True, upload_to='images/instruments/3d_models/'),
        ),
        migrations.AlterField(
            model_name='instrumentimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/instruments/detailed/images/'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/page_sections/'),
        ),
        migrations.AlterField(
            model_name='site3dcontent',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/site_content/'),
        ),
        migrations.AlterField(
            model_name='sound',
            name='sound_sample',
            field=models.FileField(blank=True, null=True, upload_to='images/instruments/sounds/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(default='team/phil.png', upload_to='images/team/'),
        ),
        migrations.AlterField(
            model_name='videotutorial',
            name='video_file',
            field=models.FileField(help_text='Upload an MP4 video file', upload_to='images/videos/tutorials/'),
        ),
    ]
