from django.contrib import admin
from .models import CustomUser, InstrumentCategory, Region, Material, InstrumentMaterial ,Instrument, Feedback, Testimonial, VideoTutorial, GuidingPrinciples, PrincipleCard, DiscoverSection, Sound, ContactPage, ContactMessage, Offering, CulturalImportance, TargetAudience, TeamMember, SocialLink, InstrumentImage, TechniqueStep, ConstructionStep, CulturalSignificance, Funfact, HomePage, Tagline, SocialMediaLink, FooterSettings, InstrumentPage, PageSection, PerformanceAppointment,LessonAppointment, InstrumentForum, InstrumentMessage, Instrument3DModel, Site3DContent, InstrumentLink

admin.site.register(CustomUser)
admin.site.register(InstrumentCategory)
admin.site.register(Region)
admin.site.register(Material)
admin.site.register(InstrumentMaterial)
admin.site.register(Instrument)
admin.site.register(Sound)
admin.site.register(Feedback)
admin.site.register(Testimonial)
admin.site.register(VideoTutorial)
admin.site.register(GuidingPrinciples)
admin.site.register(PrincipleCard)
admin.site.register(DiscoverSection)
admin.site.register(ContactPage)
admin.site.register(ContactMessage)
admin.site.register(Offering)
admin.site.register(CulturalImportance)
admin.site.register(TargetAudience)
admin.site.register(TeamMember)
admin.site.register(SocialLink)
admin.site.register(InstrumentImage)
admin.site.register(TechniqueStep)
admin.site.register(ConstructionStep)
admin.site.register(CulturalSignificance)
admin.site.register(Funfact)
admin.site.register(Tagline)
admin.site.register(HomePage)
admin.site.register(SocialMediaLink)
admin.site.register(FooterSettings)
admin.site.register(InstrumentPage)
admin.site.register(PageSection)
admin.site.register(PerformanceAppointment)
admin.site.register(LessonAppointment)
admin.site.register(InstrumentForum)
admin.site.register(InstrumentMessage)
admin.site.register(Instrument3DModel)
admin.site.register(Site3DContent)
admin.site.register(InstrumentLink)

